<?php

use Illuminate\Database\Seeder;

class PromotionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	\DB::table('promotions')->insert(array (
        		'title' => 'PROMOCIÓN INFANTO-JUVENIL',
        		'content' => '<p>INSCRIPCIONES ABIERTAS TODO EL AÑO REGISTRATE EN LINEA Y PRUEBA UNA SEMANA DE ENTRENAMIENTO GRATIS LAS CLASES SE IMPARTEN TRES VECES POR SEMANA SABADOS Y/O DOMINGOS PARTICIPAS EN TORNEOS Y CAMPEONATOS PREPARATIVOS Y OFICIALES (LUEGO DE PASAR POR UNA FASE DE ADAPTACION FISICA). HORARIOS: MATUTINOS Y VESPERTINOS (CONTACTANOS PARA INFORMARTE NUESTROS HORARIOS DE ACUERDO A TU CATEGORIA)</p>',
        		'promotion' => '1 SEMANA GRATIS DE ENTRENAMIENTO',
        		'page' => 'INFANTO-JUVENIL',
        ));

        \DB::table('promotions')->insert(array (
        		'title' => 'PROMOCIÓN FEMENINA',
        		'content' => '<p>INSCRIPCIONES ABIERTAS TODO EL AÑO REGISTRATE EN LINEA Y PRUEBA UNA SEMANA DE ENTRENAMIENTO GRATIS LAS CLASES SE IMPARTEN TRES VECES POR SEMANA SABADOS Y/O DOMINGOS PARTICIPAS EN TORNEOS Y CAMPEONATOS PREPARATIVOS Y OFICIALES (LUEGO DE PASAR POR UNA FASE DE ADAPTACION FISICA). HORARIOS: MATUTINOS Y VESPERTINOS (CONTACTANOS PARA INFORMARTE NUESTROS HORARIOS DE ACUERDO A TU CATEGORIA)</p>',
        		'promotion' => '1 SEMANA GRATIS DE ENTRENAMIENTO',
        		'page' => 'FEMENINA',
        ));

        \DB::table('promotions')->insert(array (
        		'title' => 'PROMOCIÓN GUARDAMETA',
        		'content' => '<p>INSCRIPCIONES ABIERTAS TODO EL AÑO REGISTRATE EN LINEA Y PRUEBA UNA SEMANA DE ENTRENAMIENTO GRATIS LAS CLASES SE IMPARTEN TRES VECES POR SEMANA SABADOS Y/O DOMINGOS PARTICIPAS EN TORNEOS Y CAMPEONATOS PREPARATIVOS Y OFICIALES (LUEGO DE PASAR POR UNA FASE DE ADAPTACION FISICA).HORARIOS: MATUTINOS Y VESPERTINOS (CONTACTANOS PARA INFORMARTE NUESTROS HORARIOS DE ACUERDO A TU CATEGORIA)</p>',
        		'promotion' => '1 SEMANA DE ENTRENAMIENTO GRATIS',
        		'page' => 'GUARDAMETA',
        ));

        \DB::table('promotions')->insert(array (
        		'title' => 'PROMOCIÓN VACACIONAL',
        		'content' => '<p>DISPONIBLES SOLO DURANTE VACACIONES ESCOLARES A PARTIR DE 4 AÑOS DE EDAD REGISTRATE EN LINEA Y OBTEN UN DESCUENTO EN LA MATRICULA PARA EL PROXIMO VACACIONAL EL VACACIONAL SE IMPARTEN CUATRO VECES POR SEMANA EVENTOS Y SALIDAS SORPRESAS HORARIOS: DE 08H00 A 12H30</p>',
        		'promotion' => 'DESCUENTO EN LA MATRÍCULA',
        		'page' => 'VACACIONAL',
        ));

        \DB::table('promotions')->insert(array (
        		'title' => 'PROMOCIÓN ADULTO',
        		'content' => '<p>LAS CLASES SE IMPARTEN DE LUNES A VIERNES HORARIOS: MATUTINO: 06H00 A 07H00 Y 07H30 VESPERTINO: 17H30 A 19H00 REGISTRATE EN LINEA Y OBTEN UN 25% DE DESCUENTO EN LA MATRICULA</p>',
        		'promotion' => '25% DE DESCUENTO EN LA MATRICULA',
        		'page' => 'ADULTO',
        ));

        \DB::table('promotions')->insert(array (
                'title' => 'INSCRIPCIÓN EN LINEA',
                'content' => '<p>Contenido</p>',
                'promotion' => '25% DE DESCUENTO EN LA MATRÍCULA',
                'page' => 'INSCRIPCIÓN',
        ));
    }
}
